### ISSUE TITLE
Subtle incompatibility with coursier

### ISSUE THREAD

**Issue by vil1** [Tapad/sbt-docker-compose#28] opened 2016-09-30 11:08 UTC
Projects using coursier's SBT plugin to fetch dependencies cannot use `dockerComposeTest`.

This is due to the fact that the presence of scalatest in the classpath is checked by testing if the string `"org.scalatest"` appears in the result of `testDependenciesClasspath`. But since coursier uses maven-style folder structure, the scalatest jar ends up in a folder resembling to `/home/johndoe/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalatest/scalatest_2.11/2.2.6/scalatest_2.11-2.2.6.jar`, which makes the aforementioned check fail although scalatest is present.

**Comment by kurtkopchik** [comment] 2016-09-30 14:58
Hi @vil1, I have not tested `sbt-docker-compose` with `coursier` before so thanks for submitting the issue! 

`testDependenciesClasspath` is an overridable `Task` so as a workaround with the current version of the plugin could change the Task to additionally return "org.scalatest" if you know for sure that scalatest is on the classpath. 

However, the better solution is to allow the plugin to also support the path naming convention that `coursier` uses so that the existence check for scalatest will work as intended. I've released an `1.0.12-SNAPSHOT` version with a fix for this:

`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.12-SNAPSHOT")`

Let me know if it works for you and I'll put out an official release with the changes.

**Comment by vil1** [comment] 2016-09-30 15:48
Hi @kurtkopchik, thanks for that swift reaction !

It seems to work as expected with this new regex-based check. In the meantime, I was pondering a solution using `libraryDependencies.value`, I may issue a PR during the week-end.

Cheers

**Comment by kurtkopchik** [comment] 2016-09-30 16:31
The official update with this fix has been released:
`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.12")`

Thanks again for reporting it. Closing this out as resolved for now. Looking forward to any PR's you may submit!

**Closed by kurtkopchik** 2016-09-30 16:31 UTC
