### ISSUE TITLE
Support of env_file ?

### ISSUE THREAD

**Issue by Cowa** [Tapad/sbt-docker-compose#11] opened 2016-05-18 11:58 UTC
Hello,

I have this simple `docker-compose.yml` using `env_file`:
```yml
version: '2'
services:
  users-presence-service:
    image: iadvize/users-presence-service:CORE-209
    env_file: .env

  redis:
    image: iadvize/redis:3
    env_file: .env
```

When using `docker-compose up` it works.

But through this plugin I have this:

````
...
Status: Image is up to date for iadvize/redis:3
Couldn't find env file: /var/folders/j0/r7msg51x67ggf3y8jkdm7m5c0000gp/T/.env
Waiting for container Id to be available for service 'users-presence-service' time remaining: 499
Waiting for container Id to be available for service 'users-presence-service' time remaining: 497
...
```

Am I doing something wrong? The `.env` file is on the same level of `docker-compose.yml`.
Or is there no support of `env_file`?

*Oh and it would be nice if when an error occurs (like my example: `Couldn't find env file...`) the command fails directly. I spent some time wondering why it was waiting forever the container ID...*

Thanks!

**Comment by kurtkopchik** [comment] 2016-05-18 13:42
Hi @Cowa. Thanks for opening this issue!

At the moment to use the `env_file:` docker-compose setting with the plugin the path to the file needs to be fully qualified. For example: `env_file: /Users/cowa/project/settings.env`

I've updated the README to reflect this. Let me know if making this change enables you to successfully run `dockerComposeUp`.

That being said, I'm working on removing the need to do this and will let you know when there is a version that doesn't require this modification.

**Comment by Cowa** [comment] 2016-05-18 13:50
Thanks @kurtkopchik for the answer.

However my usage is to run tests on a CI (not my machine), so I will not have the qualified path there.
I will wait :)

**Comment by kurtkopchik** [comment] 2016-05-18 15:21
Hi @Cowa. I published a `1.0.8-SNAPSHOT` release that I believe should fix the issue:
`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.8-SNAPSHOT")`

Please let me know if it works for you and if so I'll get an official release out with the change.

**Comment by Cowa** [comment] 2016-05-19 07:56
Thanks it works for `dockerComposeUp`!

But on `dockerComposeTest`, the `.env` file seems not to be properly injected.

Play framework cry when loading the configuration:
`Could not resolve substitution to a value: ${REDIS_HOST}`

But no problem on `dockerComposeUp`. So it's weird...

**Comment by tobym** [comment] 2016-05-19 12:17
Hi @Cowa, you could pull in the configuration via a system property `${redis:6379}` which is passed in to the test runner.

**Comment by kurtkopchik** [comment] 2016-05-19 12:37
It should also be noted that the test cases run by `dockerCompseTest` run outside of the docker-compose instance. They connect into the instance via the `configMap` and System property values passed into the test case which contain the dynamically assigned port and container information. From your original compose yml it looks like you are not exposing a port on your Redis service which you will have to do to connect to it from a test case using the info from @tobym 

```
  redis:
    image: iadvize/redis:3
    ports:
        - "6379"
    env_file: .env
```

Let me know if that works!

**Comment by Cowa** [comment] 2016-05-19 15:56
I understand more how it works now, thanks!

There is a problem with the system property though, `typesafe/config` doesn't allow `:` so `${redis:6379}` is not valid.

I tried with quotes `${"redis:6379"}`, but:

`Could not resolve substitution to a value: ${"redis:6379"}`

(And of course I added the port 6379 for redis)

**Comment by tobym** [comment] 2016-05-19 16:39
Good catch; yes, you need the quotes.  That looks like it should work, however.   Could you share the version of Play and typesafe config that you're using, along with the config file?

Also, potentially related: https://github.com/typesafehub/config/issues/134

**Comment by Cowa** [comment] 2016-05-19 16:57
I use Play 2.5.3 shipped with config 1.3.0.

Config file:
```
redis {
  host = ${?REDIS_HOST}
  host = ${"redis:6379"}

  port = ${?REDIS_PORT}
  port = 6379

  pool {
    max_connections = 10
    max_connections = ${?REDIS_POOL_MAX_CONNECTIONS}
  }
}
```

**Comment by tobym** [comment] 2016-05-19 17:44
Try this:

Shut down sbt, and if there is a file in /tmp/dockerComposeInstances.bin, delete it.  (This contains information about running docker-compose instances, and in 1.0.7 there is a bug which may cause the plugin to be unable to find the right instances; this is fixed in the upcoming 1.0.8 release).  Run the tests again and see if that fixed it.

**Comment by tobym** [comment] 2016-05-19 17:47
Here is a trivial app that shows the system property working in isolation of the plugin and docker: https://gist.github.com/tobym/35d0fe799a520122b98e9eebfda266aa

**Comment by kurtkopchik** [comment] 2016-05-19 18:05
@Cowa I also published and updated version of the 1.0.8-SNAPSHOT release that also includes the fix for the bug mentioned by @tobym.
`addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.8-SNAPSHOT")`

When you have a moment please refresh your plugins and give it another try. If it still fails if we could get the full output from the `dockerComposeTest` command that would help us track down the root cause. 

Thanks!

**Comment by Cowa** [comment] 2016-05-19 18:24
Yeah! It works by removing `dockerComposeInstances.bin`, thanks @tobym.

@kurtkopchik All is okay with this new snapshot too.

Well, everything seems fine now. Thank you again to both of you :+1:

**Comment by kurtkopchik** [comment] 2016-05-19 18:33
Excellent! I'm glad you are now up and running with the plugin. I'll let you know when the official release with these changes gets published.

**Comment by kurtkopchik** [comment] 2016-05-19 19:47
The official 1.0.8 release has been published: `addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.8")`

Please open a new issue if you run into any other problems. Thanks again for using the plugin!

**Closed by kurtkopchik** 2016-05-19 19:47 UTC
